package com.sj.oa.project.service.demerit;

import com.sj.oa.project.po.demerit.Demerit;

import java.util.List;

public interface IDemeritService {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKeys(String[] id) throws Exception ;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int insertSelective(Demerit demerit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    Demerit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Demerit demerit) throws Exception;

    /**
     *
     * @描述 扣分列表
     *
     * @date 2018/9/15 13:39
     */
    List<Demerit> selectDemeritList(Demerit demerit);

    /**
     * 校验扣分代码是否唯一
     *
     * @param demerit 专业信息
     * @return 结果
     */
    public String checkDemeritCodeUnique(Demerit demerit);


    Demerit findDnumber(String dCode);
}
