package com.sj.oa.project.service.demerit;


import com.sj.oa.project.po.demerit.DemeritType;

import java.util.List;

public interface IDemeritTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKeys(String[] id) throws Exception ;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int insertSelective(DemeritType demerittype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    DemeritType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemeritType demerittype) throws Exception;

    /**
     *
     * @描述 扣分类型列表
     *
     * @date 2018/9/15 13:39
     */
    List<DemeritType> selectDemeritTypeList(DemeritType demerittype);

    /**
     * 校验扣分代码是否唯一
     *
     * @param demerittype 专业信息
     * @return 结果
     */
    public String checkDemeritTypeUnique(DemeritType demerittype);
}
