package com.sj.oa.project.service.college;

import com.sj.oa.project.po.college.Classall;

import java.util.List;

/**
 * Created by dell on 2019-08-03.
 */
public interface IClassService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKeys(Integer[] id) throws Exception ;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int insertSelective(Classall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    Classall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Classall record) throws Exception;

    /**
     *
     * @描述 专业列表
     *
     * @date 2018/9/15 13:39
     */
    List<Classall> selectClassList(Classall classall);

    /**
     * @描述: 查询所有专业下的所有班级 班级归类 树状数据
     * @return
     */
    List<Classall> selectClassAndMajor();

    /**
     * 校验班级名称
     * @param record
     * @return
     */
    String checkClassNameUnique(Classall record);

}
