package com.sj.oa.project.service.major;

import com.sj.oa.project.po.college.Major;

import java.util.List;

/**
 * Created by dell on 2019-08-03.
 */
public interface IMajorService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKeys(String[] id) throws Exception ;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    Major selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Major record) throws Exception;

    /**
     *
     * @描述 专业列表
     *
     * @date 2018/9/15 13:39
     */
    List<Major> selectMajorList(Major major);

    /**
     * 校验专业名称是否唯一
     *
     * @param major 专业信息
     * @return 结果
     */
    public String checkMajorNameUnique(Major major);

    /**
     * 校验专业代码是否唯一
     *
     * @param major 专业信息
     * @return 结果
     */
    public String checkMajorCodeUnique(Major major);

}
